### PR TITLE
[WIP] ExceptionListener: fix deprecations from SF 4.3

### PR DESCRIPTION
**Pull request by thePanz**

### CODE REVIEW

**Comment by maxhelias** [comment]
I'm not sure but I think this is not the right approach because the `EventSubscriberInterface` interface registers a new action on `onKernelException` so `HttpKernelExceptionListener` is executed twice.
I would go on a decorator but I don't know the purpose of `ZONE_ATTRIBUTE`

**Comment by maxhelias** [comment]
Related #2017

**Comment by thePanz** [comment]
I agree, I thought it would be a straightforward fix, but it is not
Furthermore: the HttpKernelExceptionListener is passing a FlattenException instead of the \Exception object.

@maxhelias Feel free to close this PR or continue working on ti :)

**Comment by maxhelias** [comment]
@thePanz, I do not know, I'm not the owner. Maybe that's the purpose to calling twice

**Comment by XWB** [comment]
Should be fixed in https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2025

**Pull request closed without merging**
