### PR TITLE
Fix phpunit deprecations

### PR DESCRIPTION
**Pull request by Ener-Getick**
see https://github.com/symfony/symfony/issues/19125

### CODE REVIEW

**Comment by Ener-Getick** [comment]
Tests fixed :)

**Comment by xabbuh** [comment]
@Ener-Getick Shouldn't we do this for the `1.7` branch first?

**Comment by Ener-Getick** [comment]
Do we still support the ``1.7`` branch ?

**Comment by xabbuh** [comment]
Apparently we may have to dicuss that. :)

**Comment by Ener-Getick** [comment]
@xabbuh so is that ok now if i merge that in 1.8 ? :)

**Comment by xabbuh** [comment]
@Ener-Getick Let me do that for you. ;) Thanks!

**Comment by Ener-Getick** [comment]
Thanks to you 😉

**Pull request merged**
