### PR TITLE
[1.7] Improve the ViolationFormatter output message

### PR DESCRIPTION
**Pull request by Ener-Getick**
This exception message looks weird to me and hard to understand, WDYT?

### CODE REVIEW

**Comment by Ener-Getick** [comment]
Well maybe we can consider this as a BC break (users might relly on it) so I don't know...

**Comment by lsmith77** [comment]
maybe just put it into 1.8?

**Comment by Ener-Getick** [comment]
:+1:

**Comment by xabbuh** [comment]
I am okay for 1.7 too. You shouldn't rely on a third-party's exceptions messages imo.

**Comment by Ener-Getick** [comment]
That was the only way to match this exception until now so i wouldn't be surprise if someone rely on its message.
As @lsmith77 i think this is safer to put this in 1.8 and to document the change.

BTW it would be great to create more custom exceptions in 2.0.

**Comment by xabbuh** [comment]
Hm, that's true. But then we can only make this change in 2.0. I agree with you about using more custom exceptions (though that doesn't help here as the exception directly leads to a response).

**Comment by Ener-Getick** [comment]
You're right, i close this in favor of https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1453 then.
BTW as i'm thinking about it, we could provide a default configuration for the exception controller to convert common exceptions that are safe (including this one).

**Pull request closed without merging**
