### PR TITLE
Make aliases private

### PR DESCRIPTION
**Pull request by GuilhemN**
Fix https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1652 by making aliases private (this way they are automatically removed).

### CODE REVIEW

**Comment by xabbuh** [comment]
Should we really apply this latch so broadly? It could break applications where people rely on the aliases being public.

**Comment by GuilhemN** [comment]
I don't think people depend on this aliases,  they're not documented anywhere nor useful for the end user (why would someone use `fos_rest.validator` instead of `validator`?).

**Comment by xabbuh** [comment]
I am not sure. They shouldn't, but that doesn't it's not happening. But we could agree on this being an unsupported use case and make the changes you suggested nonetheless.

**Comment by GuilhemN** [comment]
@xabbuh imo this is not worth a bc layer :) No one should rely on that.

**Comment by xabbuh** [comment]
:+1: let's do it then :)

**Comment by GuilhemN** [comment]
Ok, thanks ☺

**Comment by GuilhemN** [comment]
Well after rethinking about it we should just revert this PR, it did only bring unwanted effects without solving https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1652. Sorry for that...

**Pull request merged**
