### PR TITLE
Merge branch 1.8 into master

### PR DESCRIPTION
**Pull request by Ener-Getick**

### CODE REVIEW

**Comment by Ener-Getick** [comment]
Did I miss something?

**Comment by xabbuh** [comment]
It looks strange to me that there are so many changes given that I merged the `1.8` branch into the `master` branch earlier today (see #1323).

**Comment by Ener-Getick** [comment]
Did you run ``git fetch`` before?

**Comment by xabbuh** [comment]
Yes, and the diff was defintely not what it looks like now when looking at #1323.

**Comment by xabbuh** [comment]
Hm, why does this remove all the serialization context related classes?

**Comment by Ener-Getick** [comment]
Yeah that happens some time I don't why... 
Did you base your new branch on your local branch 1.8 or on the fosrest one?

**Comment by Ener-Getick** [comment]
I removed them because we decided to take a different approach (the ``Serializer`` interface).

**Comment by xabbuh** [comment]
I based it on the remote branch. And when I take a look at the history of the `MERGE1.8` branch, I can see some commits twice. For example, take a look at https://github.com/FriendsOfSymfony/FOSRestBundle/commits/MERGE1.8?page=2 and you will see the commit with message "do not overwrite explicit templates, fix issues with redirects" twice at December 28.

**Comment by Ener-Getick** [comment]
Hum that's strange... Moreover one of them has been committed by me. 
That's possible that I rebased my branch too fast and that I changed some commits hash...

**Comment by Ener-Getick** [comment]
screenshot_2016-01-23-17-26-56
Anyway as you can see in this screenshot some commits weren't merged in master by your PR.

**Comment by xabbuh** [comment]
Yeah, GitHub is showing me the same. It might have been too late when I made the merge. :(

**Comment by Ener-Getick** [comment]
No idea ^_^ and unrelated by I won't be at home this week so if you review this feel free to merge it 😉
Otherwise I'll review it deeper next week.

**Comment by xabbuh** [comment]
Yeah, I will try to find the cause and otherwise merge here in case I don't find anything weird. :)

**Comment by xabbuh** [comment]
Oh, I noticed my mistake. I merged 1.7 into master. :(

**Comment by Ener-Getick** [comment]
Hum this explains some things 😝

**Pull request merged**
