### PR TITLE
Mark many classes/methods as private/internal

### PR DESCRIPTION
**Pull request by Ener-Getick**
Relates to #1243 and #1244

### CODE REVIEW

**Comment by xabbuh** [comment]
I think we should do that step in 1.8 instead so that people could already check before the next major version if there could would work well.

**Comment by xabbuh** [comment]
Well, actually I would split the PR: adding the `@internal` annotation in 1.8 and changing the visibility in 2.0.

**Comment by Ener-Getick** [comment]
You're right I'll create another PR for 1.8

**Comment by Ener-Getick** [comment]
See #1258

**Comment by Ener-Getick** [comment]
Closes #1244

**Pull request merged**
