### PR TITLE
Forbid SensioFrameworkExtraBundle >= 3.0.13

### PR DESCRIPTION
**Pull request by Ener-Getick**
See https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1354#issuecomment-187678100

### CODE REVIEW

**Comment by lsmith77** [comment]
+1

Status: Reviewed

**Comment by merk** [comment]
Do we have to force users to upgrade to 2.0 to actually get a proper fix here?

**Comment by Ener-Getick** [comment]
@merk it would need a lot of logic to support both SensioFrameworkExtraBundle 2.0 and 3.0, so except if someone wants to create a PR to backport the fix to 1.8, people have to upgrade to 2.0.

**Comment by xabbuh** [comment]
@Ener-Getick Can't we revert this change when a new version of SensioFrameworkExtraBundle gets released?

**Comment by merk** [comment]
No, the change made in that PR fixes a new issue exposed with the new implementation in 2.0, not ~1.7

**Comment by Ener-Getick** [comment]
@xabbuh no that won't be possible unless we refactor the ``ViewResponseListener`` in ``1.*``.

**Comment by xabbuh** [comment]
@merk @Ener-Getick Thanks for clarifying. I guess that's not worth it (at least not right now, we may reconsider that in the future though).

**Pull request merged**
