### PR TITLE
handling key for groups

### PR DESCRIPTION
**Pull request by Rewieer**
This is a PR to solve #1737

### CODE REVIEW

**Comment by GuilhemN** [comment]
Duplicate of https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1716

I did not have the time to look at it but at first sight I don't really like it, I'd prefer having a `setGroups` method and maybe even deprecate the adders.

**Comment by Rewieer** [comment]
This method is quite cheap I must admit, but a setGroups method requires more work, and this feature is quite important. Can't we put it "as is" for now (it doesn't really decrease code readibility or so) and refactor the group part later ?

**Comment by GuilhemN** [comment]
Rethinking about it, I don't think that's the right solution, I would rather prefer using `setGroups` with `array_merge` in our code.

**Comment by Rewieer** [comment]
So you want me to remove addGroup and add a setGroups function. I will try to.

**Comment by GuilhemN** [comment]
There is already a `setGroups` function, we just need to use it. See https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1740 :)

**Comment by GuilhemN** [comment]
Closing as https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1740 is merged.

**Pull request closed without merging**
