### PR TITLE
Ignoring PSR7 request typehint in route loader

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by Ener-Getick** [comment]
In fact didn't it break because of the use of reflection? As we removed it, i think we can safelly readd the interface directly.

**Comment by xabbuh** [comment]
@Ener-Getick You are right. I removed my commit and kept only the one from #1229.

**Comment by Ener-Getick** [comment]
Thank you @xabbuh

**Comment by claudiobizzotto** [comment]
Awesome! Thanks :thumbsup:

**Pull request merged**
