### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by Ener-Getick**

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1:

**Comment by Ener-Getick** [comment]
Relates to https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1318

**Comment by xabbuh** [comment]
Thank you @Ener-Getick.

**Comment by Ener-Getick** [comment]
I think there is another error in this pr sorry I didn't mention it :x

**Comment by Ener-Getick** [comment]
I'll check it in a few hours.

**Pull request merged**
