### PR TITLE
1.8

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by Ener-Getick** [comment]
You can't merge this because of the required statuses :x

**Comment by hacfi** [comment]
Can this be merged or should someone create a new PR for this?

**Comment by Ener-Getick** [comment]
@hacfi we have to create a new pr based on master :x

If you want to do it that would be really helpful ☺

**Comment by hacfi** [comment]
Sure. Hope @xabbuh doesn’t mind I’m stealing his PR :).

Should I cherrypick the 1.8 commits or make those changes manually?

**Comment by Ener-Getick** [comment]
You just have to have to run ``git checkout -b merge1.8 upstream/master & git merge upstream/1.8`` normally 😉

**Comment by hacfi** [comment]
Thx @Ener-Getick - just wasn’t sure if that merges unwanted stuff as well but worked fine: PR #1336

**Comment by xabbuh** [comment]
Thanks for handling this @hacfi! :)

**Pull request closed without merging**
