### PR TITLE
fixes several issues to make the CI pass again

### PR DESCRIPTION
**Pull request by smoench**
This PR fixes several issues to make the CI pass again:
- drops support for Symfony <5.4
- allows doctrine/annotations 2.0 in the require dev
- solves PHP 8.2 deprecations
- solves Symfony 6+ deprecations
- increases indirect deprecation count to solve issues with FrameworkExtraBundle

### CODE REVIEW

**Review by deluxetom — APPROVED** [review]

**Comment by raziel057** [comment]
@smoench Nice, I was doing the same but yours is more complete.

**Comment by smoench** [comment]
Hey @goetas, you might have some time to review this PR and let me know if you fine with it. I mean the most controversial might be the drop of Symfony <5.4 support but they are [EOL](https://symfony.com/releases#symfony-releases-calendar). Thanks in advance :-)

**Comment by shakaran** [comment]
Note that if this get merged, the PR at https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2388 could be closed, since this one include that changes

**Comment by deluxetom** [comment]
any luck merging this PR? quite a lot of issues with Symfony 6.3

**Pull request merged**
