### PR TITLE
Removed useless interfaces

### PR DESCRIPTION
**Pull request by Ener-Getick**
This PR removes several interfaces:
* ParamFetcherInterface
* ViolationFormatterInterface
* ViewHandlerInterface
* ConfigurableViewHandlerInterface

### CODE REVIEW

**Comment by lsmith77** [comment]
what is the logic here? that these classes should be extended only via inheritance?

**Comment by Ener-Getick** [comment]
Yeah I don't see any use case for this interfaces. 
I opened this PR to discuss about it. (I forgot to add a message describing the issue)

**Comment by xabbuh** [comment]
I think we should only remove interfaces when there is no need for custom implementations of a class. And then we should make our own implementation final.

**Comment by Ener-Getick** [comment]
Well imo this classes can be extended but there is no need to provide a complete implementation.

**Comment by stof** [comment]
@Ener-Getick Inheritance is generally a worse way to provide an extension point than composition (and much harder to provide BC btw).
So making inheritance the recommended extension is a big -1 from me. I would rather have an interface to allow composition and forbig inheritance.

The issue with the ViewHandler is of course that it has far too many responsibilities, making it impossible to use composition to provide useful extension points.

**Comment by Ener-Getick** [comment]
Makes sense. Instead of removing them we should probably find a way to improve them.

**Pull request closed without merging**
