### PR TITLE
deprecate using the ControllerNameParser

### LINKED ISSUE #2057: Symfony 4.4 controller_name_converter deprecation
When I run: 
```bash
php bin/console debug:config fos_rest
```
It gives me: 
```bash
2020-01-25T13:43:03+00:00 [info] User Deprecated: The "controller_name_converter" service is deprecated since Symfony 4.3. It is being referenced by the "fos_rest.routing.loader.controller" service.
```

I know there are other issues with a similar output but what is the way to fix this, if it is a problem

### PR DESCRIPTION
**Pull request by xabbuh**
fixes #2057

### CODE REVIEW

**Comment by kevinpapst** [comment]
Thanks @xabbuh 👍 Updating to this branch results in:
Bildschirmfoto 2020-02-02 um 18 28 14
When setting the new config:
```
    routing_loader:
        parse_controller_name: false
```
all deprecations are gone. For me no behavioral changes are visible, all my tests are green with either setting.

**Comment by xabbuh** [comment]
@kevinpapst Thank you for giving it a try.

**Comment by XWB** [comment]
Good work @xabbuh

**Comment by fahimbinkhair** [comment]
Hi @kevinpapst 
I am getting this message with symfoy 4.4 but not understanding what to do to get rid of this.
The message looks like

1x: The "controller_name_converter" service is deprecated since Symfony 4.3. It is being referenced by the "fos_rest.routing.loader.controller" service.

Can you please advice
Thanks

**Comment by kevinpapst** [comment]
AFAIK this is not yet released. Will be included in 2.8 according to the UPGRADING guide.
Maybe @xabbuh has a timeline on this?

**Pull request merged**
