### PR TITLE
Removing conflicting validation rule.

### PR DESCRIPTION
**Pull request by kherge**
While PR #321 added support for using both serialization groups and versions, the configuration validation was not updated to reflect these changes. This commit simply removes the specific validation rule that is affected.

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1:

**Comment by Ener-Getick** [comment]
:+1:

**Comment by xabbuh** [comment]
Thank you for the fix and a happy new year @kherge!

**Comment by kherge** [comment]
Happy to help and happy New Years to you too!

**Pull request merged**
