### PR TITLE
Add support \Twig_Template on set template.

### PR DESCRIPTION
**Pull request by liverbool**
Add support \Twig_Template on set template.

### CODE REVIEW

**Comment by stof** [comment]
what is the use case for passing the Twig_Template instance rather than the template name ?

**Comment by liverbool** [comment]
@stof when we need to create template from string.

```php
$template = $twig->createTemplate("Example {{ string }}");
$view = View::create();
$view->setTemplate($template);
// ...
```

**Comment by Ener-Getick** [comment]
Can you add tests for that please?

**Comment by Ener-Getick** [comment]
Can you also add a functional test? I'm not sure it will work nicely with the rest of the `ViewHandler`.

**Comment by Tobion** [comment]
Closing as the namespaces twig classes should be used now. So this is outdated in its current form.

**Pull request closed without merging**
