### PR TITLE
2.5 validator API compatibility

### PR DESCRIPTION
**Pull request by lsmith77**
@alekitto .. I took the liberty of opening a PR for you. it seems like you are working on an earlier branch of master, so you will need to rebase your branch.

fix for https://github.com/FriendsOfSymfony/FOSRestBundle/issues/846

### CODE REVIEW

**Comment by alekitto** [comment]
@lsmith77 I rebased my work onto current master. Still needs tests.

**Comment by lsmith77** [comment]
looking good so far. @stof might have some feedback

**Comment by stof** [comment]
:+1:

**Comment by lsmith77** [comment]
@stof something seemed to have gone wrong with scrutinizer when I wanted to check the code coverage. I guess in general specifically testing this will be hard but I guess we sort of test it, since we test multiple Symfony versions .. as such .. I guess we can just merge this?

**Pull request merged**
