### PR TITLE
Add view format constants

### PR DESCRIPTION
**Pull request by ihsanudin**
Add view format constants

purpose this issue #1408

### CODE REVIEW

**Comment by Ener-Getick** [comment]
I'm not convinced that this is useful as the value of this constants will never change and is very intuitive.

**Comment by sstok** [comment]
An FORMAT_HTML constant for 'html', that's a bit overdoing it :) for status codes I would say yes but in this case :-1:

**Comment by ihsanudin** [comment]
@sstok : it's just my case, i don't know how many format can be supported by FOSRestBundle and we need to know that

**Comment by Ener-Getick** [comment]
@ihsanudin in what would this help you? do you have any real examples?

**Comment by ihsanudin** [comment]
This is my example

```lang=php
$view = View::create()
            ->setStatusCode(Response::HTTP_OK)
            ->setFormat(View::FORMAT_HTML)
            ->setTemplate('template.html.twig')
        ;
```
With that constants, My IDE can suggest (auto complete) the view format. It's more efficient and easier for me

**Comment by xabbuh** [comment]
Usually I would agree that adding constants to improve the developer experience through auto-completion was a nice improvement. However, in this concrete example I feel that this might lead to the misperception that we only support the given three formats which might confuse people.

**Comment by Ener-Getick** [comment]
Then I guess we can close this.
Thank you for your contribution anyway @ihsanudin :-)

**Pull request closed without merging**
