### PR TITLE
Change docblock return value to 'static'

### PR DESCRIPTION
**Pull request by rokkie**
When creating a new instance using the 'static' keyword but the
docblock uses the class name, autocomplete can't figure out the late
static binding. Changing this to 'static' fixes this.

### CODE REVIEW

**Comment by Ener-Getick** [comment]
IMO it should also be changed for ``createRedirect``.

**Comment by Ener-Getick** [comment]
Would be better to target ``1.8`` instead of ``master``.

**Comment by rokkie** [comment]
Should I create a new PR for this?

**Comment by Ener-Getick** [comment]
Just rebase this one on ``1.8``, it will do the trick.

**Comment by rokkie** [comment]
I rebased the branch, however, PR still seems to want to merge into master.

**Comment by Ener-Getick** [comment]
I created #1273. I thought I could merge your changes with the command lines but it didn't work...

Anyway, thank you @rokkie.

**Pull request closed without merging**
