### PR TITLE
Rename AbstractScalarParameter::$array to ::$map

### PR DESCRIPTION
**Pull request by Ener-Getick**
Relates to https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1190#issuecomment-154802257

### CODE REVIEW

**Comment by lsmith77** [comment]
would be good to add a test case and mention this in the docs

**Comment by Ener-Getick** [comment]
This is just a rename, there is already a test for this. And is this https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1191/files#diff-2bf0083cfe57bb37a1bf4800c70a2733R61 not enough ?

**Comment by lsmith77** [comment]
well it would be good to also test with an associative array

**Comment by lsmith77** [comment]
@Ener-Getick FYI I have you write permissions on this repo .. as you know its still best to work through PRs and branches but this makes it easier to collaborate

**Comment by Ener-Getick** [comment]
Thanks, so from now I have to use a branch on the official repo for my PRs?

**Comment by lsmith77** [comment]
@Ener-Getick yeah that would be best. And of course you can now add tags, close/edit tickets

**Comment by Ener-Getick** [comment]
Hum, I just see that there is a type check here https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Controller/Annotations/AbstractScalarParam.php#L36. 
IMO, we should not create a new option, maybe create a new class containing several constants:
```php
<?php

class ValidationStrategy {
    const RAW = 0;
    const MAP = 1;
}
```

And then we would use it in our annotation: 
```php
/**
 * @RequestParameter(array=ValidationStrategy::MAP)
 */
```
If ``array === true``, the default value would be ``ValidationStrategy::map``.

Another solution would be to just remove this type check.

**Comment by Ener-Getick** [comment]
I think that the best solution is to remove this type check as we don't know what the user wants...
We can in another PR add a ``type`` validation.

**Comment by lsmith77** [comment]
the build error seems to be an issue with the PHP7 setup on travis:
https://travis-ci.org/FriendsOfSymfony/FOSRestBundle/jobs/91239000

**Comment by Ener-Getick** [comment]
I'll try to relaunch the Travis build tomorrow it doesn't seem to be caused by our config...

**Comment by lsmith77** [comment]
build is fixed again

**Comment by Ener-Getick** [comment]
Ok, I will rebase this PR tonight. 

I do not remember why I added this type check, there were nothing similar before...

**Comment by stof** [comment]
I suggest providing a BC layer for this, to make it easier to migrate to the new version of the bundle. It should not be hard to keep support for the old signature of the annotation for now

**Comment by Ener-Getick** [comment]
I will create a pr with bc layers for the last bc breaks.

**Comment by Ener-Getick** [comment]
See #1213

**Comment by Ener-Getick** [comment]
For me everything is ok. 
Can I merge this PR @lsmith77 ?

**Pull request merged**
