### PR TITLE
point to symfony.com for the docs

### PR DESCRIPTION
**Pull request by lsmith77**
waiting on the symfony.com update

fix for https://github.com/FriendsOfSymfony/FOSRestBundle/issues/931

### CODE REVIEW

**Comment by lsmith77** [comment]
@javiereguiluz / @fabpot please let me know when its ready, so that I can merge and release 1.5.0

**Comment by fabpot** [comment]
@lsmith77 This is about to be deployed, should be done today. I will ping you when everything is working fine on our side.

**Comment by fabpot** [comment]
Done: http://symfony.com/doc/master/bundles/FOSRestBundle/index.html

**Comment by lsmith77** [comment]
merci!

**Pull request merged**
