### PR TITLE
Replace references to "Symfony2" with "Symfony"

### PR DESCRIPTION
**Pull request by phansys**
| Q             | A
| ------------- | ---
| Branch        | 2.0
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |

Replace references to "Symfony2" with "Symfony" since this bundle is compatible
with Symfony 3.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
👍

**Comment by Ener-Getick** [comment]
:+1: to merged this in 1.8.

**Comment by xabbuh** [comment]
Thank you @phansys!

**Comment by phansys** [comment]
Thank you @xabbuh. Please note that repo description should be updated accordingly:
>This Bundle provides various tools to rapidly develop RESTful API's with Symfony2

**Comment by xabbuh** [comment]
@Ener-Getick @lsmith77 Can anyone of you update the repo description?

**Comment by Ener-Getick** [comment]
Done ☺

**Pull request closed without merging**
