### PR TITLE
don't use deprecated routing features

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by lsmith77** [comment]
when were these features deprecated?

**Comment by xabbuh** [comment]
In 2.2 if I am not mistaken.

**Comment by lsmith77** [comment]
ok .. I just noticed that in the composer.json we still support 2.2, while in travis we only test against 2.3:
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/composer.json#L26
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/.travis.yml

I guess we should also bump this to 2.3 in composer. Meaning there might be even more stuff to remove then.

**Comment by lsmith77** [comment]
see also https://github.com/FriendsOfSymfony/FOSRestBundle/pull/952

**Pull request merged**
