### PR TITLE
[1.8] Mark classes/methods as internal

### PR DESCRIPTION
**Pull request by Ener-Getick**
Relates to #1243

### CODE REVIEW

**Comment by Ener-Getick** [comment]
Did I miss something ?

**Comment by Ener-Getick** [comment]
Closes #1243

**Comment by stof** [comment]
@Ener-Getick check also for any class which is in 1.8 but not yet in 1.7, as these can be switched to private visibility already (as they are not yet released)

**Comment by Ener-Getick** [comment]
There is nothing in 1.8 for the moment https://github.com/FriendsOfSymfony/FOSRestBundle/compare/1.7...1.8

**Comment by Ener-Getick** [comment]
@lsmith77 @xabbuh do you something else to mark as internal or can I merge this PR ?

**Comment by xabbuh** [comment]
:+1: looks good to me, this just needs a rebase

**Pull request merged**
