### PR TITLE
handle throwable

### PR DESCRIPTION
**Pull request by fprochazka**

### CODE REVIEW

**Comment by xabbuh** [comment]
I am not sure if we should update the docs this way. If this is your application, you will know if you run it on PHP 7 and in this case you could simply stop catching `\Exception` but catch `\Throwable` instead (there is no need to have both). Maybe we should simply add a comment that you can catch `\Throwable` instead when using PHP 7.

**Comment by fprochazka** [comment]
Oh, you're right, I didn't notice it's only the doc. So this can be closed then?

**Comment by Ener-Getick** [comment]
I'm :-1: for this PR as it targets docs but the others are relevant ;-)

**Comment by fprochazka** [comment]
Ok, np :)

**Pull request closed without merging**
