### PR TITLE
Fix issue with redirect

### PR DESCRIPTION
**Pull request by lsmith77**
this includes a merge of 1.7

### CODE REVIEW

**Comment by Ener-Getick** [comment]
Needs a rebase ;-)

**Comment by lsmith77** [comment]
How so? Looks fine to me

**Comment by Ener-Getick** [comment]
> This branch is out-of-date with the base branch

Did you run ``git fetch``?

**Comment by Ener-Getick** [comment]
I rebased your commits ;-) 
You can run ``git pull -f``

**Comment by lsmith77** [comment]
looks good I guess ..

**Comment by Ener-Getick** [comment]
Yeah, everything has been said in #1250 normally.

**Pull request merged**
