### PR TITLE
bump PHPUnit version and fix php 8 support

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by GuilhemN** [comment]
:+1: I did not realize you were still maintaining v2. So yes it's better to do this in 2.x to simplify future merge conflicts.

**Comment by GuilhemN** [comment]
I think we can safely merge this :)

**Comment by kevinpapst** [comment]
I know at least one project that would be very happy to see this tagged (in v3) 😁 and I guess there are 100+ more who are just waiting silently.

Thanks for taking care of it! 👍

**Comment by GuilhemN** [comment]
https://github.com/FriendsOfSymfony/FOSRestBundle/releases/tag/3.0.4 done :)

**Comment by kevinpapst** [comment]
Thank you both!!!!

**Pull request merged**
