### PR TITLE
Fix custom message not used on access denied exception

### PR DESCRIPTION
**Pull request by lolmx**
When using `$this->createAccessDeniedException($customMessage)` in a controller, the response will always be:

    {
        code: 403,
        message: "You do not have the necessary permissions"
    }

This is caused by the AccessDeniedListener which is overriding the exception message. Here's a proposal to allow custom messages.

### CODE REVIEW

**Comment by qdequippe** [comment]
+1 to have custom messages

**Comment by lolmx** [comment]
The Travis build fails because the tests explicitly expect the message `You are not authenticated` for  [UnauthorizedHttpException](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/EventListener/AccessDeniedListener.php#L77) and [HttpException](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/EventListener/AccessDeniedListener.php#L79).

Should we allow custom messages for those two exceptions too (need updating the tests [here](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Tests/EventListener/AccessDeniedListenerTest.php#L151)) or not?

**Comment by Ener-Getick** [comment]
:+1: but do we really still need this listener ?
Using the exception listener, it's easy to use a different status code depending of the exception.

**Comment by lolmx** [comment]
I don't know if the listener is still needed, but it's actually used.
[Here](https://github.com/lolmx/FOSRestBundle/blob/master/Resources/config/access_denied_listener.xml) it's declared as a service.

And because of the [priority](https://github.com/lolmx/FOSRestBundle/blob/master/EventListener/AccessDeniedListener.php#L90), the AccessDeniedListener will be called before the [ExceptionListener](https://github.com/lolmx/FOSRestBundle/blob/master/EventListener/ExceptionListener.php#L50). Once in the ExceptionListener, my custom message is lost yet, replaced by the `You do not have the necessary permissions`message.

**Comment by Ener-Getick** [comment]
@lolmx you can disable it for now at least:
```yml
fos_rest:
    access_denied_listener: false

**Comment by lolmx** [comment]
Indeed, I got my messages thanks :)

Should I close this PR?

**Comment by Ener-Getick** [comment]
@lolmx i would prefer to have someone else point of view before :)

**Comment by lsmith77** [comment]
to me its also a security question .. exception messages can leak internals. this is why in the exception controller we by default do not include the message in the response.

**Comment by Ener-Getick** [comment]
@lsmith77 ok thanks :) then i think we should add a note in the docs saying that this listener should not be used to keep custom messages.

Thank you @lolmx !

**Pull request closed without merging**
