### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by lyrixx**
See: https://github.com/FriendsOfSymfony/FOSRestBundle/blob/1.5/DependencyInjection/Compiler/SerializerConfigurationPass.php#L24

### CODE REVIEW

**Comment by GuilhemN** [comment]
Actually it is talking about the config here.

**Comment by lyrixx** [comment]
> Actually it is talking about the config here.

I did not understand your comment. What do you mean?

**Comment by lyrixx** [comment]
And BTW, the order is wrong (at least in for 2.0)

**Comment by GuilhemN** [comment]
I'm refering to the [Configuration](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/DependencyInjection/Configuration.php#L119). But there's still a typo, it should be `fos_rest.service.serializer`.

**Comment by lyrixx** [comment]
I detected this issue, because in my project I have the SF serializer **and** the JMS one. But, for legacy reason, fos rest should use the JMS one. And right now, it's not possible with ease. The only solution I see is to create a compiler pass, that should pass **after** your to update the alias.

(I'm using 2.0)

**Comment by GuilhemN** [comment]
https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1622 fixes it :)

**Comment by lyrixx** [comment]
I don't understand the code here. There is a configuration available, but it can not find where it is used.

Then, in the [pass](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/DependencyInjection/Compiler/SerializerConfigurationPass.php#L29) the code is looking for a service with id `fos_rest.serializer`.

**Comment by GuilhemN** [comment]
It is used [here](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/DependencyInjection/FOSRestExtension.php#L66-L70) and creates this services.

**Comment by xabbuh** [comment]
Though I think that we could indeed improve this sentence to become something like this:

The one you configured using the `fos_rest.service.serializer` option (if you did).

Beware that you will probably have to rebase your changes on the `2.0` branch (the service/services mismatch is already solved on that branch).

**Pull request closed without merging**
