### PR TITLE
[FormatNegotiator] Re-add the ability to transform automatically most common mime types when using symfony 3.1

### PR DESCRIPTION
**Pull request by Ener-Getick**
Re-add the ability to transform automatically most common mime types.

See https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1149#discussion-diff-41261255

### CODE REVIEW

**Comment by lsmith77** [comment]
maybe also mention this in the changelog?

**Comment by Ener-Getick** [comment]
Done @lsmith77 :smiley:

**Comment by Ener-Getick** [comment]
I fixed the tests

**Comment by lsmith77** [comment]
do we want to wait until 3.1 is out or merge this already, its unlikely that this will be reverted I guess.

**Comment by Ener-Getick** [comment]
Hum didn't see that from this point of view... 
I think we can already merge it that would allow people to migrate to FOSRestBundle 2.0 easily and if it is ever reverted we can just revert this changes too.

**Comment by Ener-Getick** [comment]
@lsmith77 @xabbuh what do you think about using something a bit dirty with ``\ReflectionClass`` for sf < 3.1 to access ``Request::$formats`` ?

**Comment by Ener-Getick** [comment]
@lsmith77 @xabbuh is this ok for you ? It would be easier for people to migrate to FOSRestBundle with this patch.

**Comment by Ener-Getick** [comment]
ping

**Comment by xabbuh** [comment]
:+1: looks good to me

**Pull request merged**
