### PR TITLE
Add fos rest info in the symfony serialization context

### LINKED ISSUE #2292: FlattenExceptionNormalizer serializes exceptions for the messenger consumer
`\FOS\RestBundle\Serializer\Normalizer\FlattenExceptionNormalizer` serializes exceptions for the messenger consumer instead of letting `\Symfony\Component\Messenger\Transport\Serialization\Normalizer\FlattenExceptionNormalizer` do the serialization and deserialization when is being run by the messenger consumer.

This causes an error when the messenger consumer tries to deserialize the exception... how can i have FOS rest not "overriding" the FlattenExceptionNormalizer provided by the messenger component? 

Disabling the exception handling done by FOS solves the problem, but I would like to keep it... 
```yaml
fos_rest:
    exception:
        enabled: false
```

### PR DESCRIPTION
**Pull request by goetas**
Fixes https://github.com/FriendsOfSymfony/FOSRestBundle/issues/2292

using same approach as in https://github.com/symfony/messenger/blob/1cc72a00521c69219ba79b7b04757d5e7fface66/Transport/Serialization/Normalizer/FlattenExceptionNormalizer.php#L98

### CODE REVIEW

**Comment by goetas** [comment]
I do not really understand how the error controller should work... how is `\FOS\RestBundle\ErrorRenderer\SerializerErrorRenderer` triggered?

**Comment by monteiro** [comment]
@goetas maybe seeing the units tests: https://github.com/FriendsOfSymfony/FOSRestBundle/blob/8779ceebf715d1c60bd10286fce9d32ed03c484a/Tests/ErrorRenderer/SerializerErrorRendererTest.php can give a hint?

If you have xdebug, it's perfect sometimes to understand the flow of the code. You can call the API and catch it on phpstorm or some IDE with xdebug support.

**Comment by erikas-tranauskas** [comment]
Any news about this one? I have this problem with exception enabled, RabbitMQ queue doesn't understand the returned exception.

**Comment by GuilhemN** [comment]
@erikas-tranauskas currents maintainers of the bundle unfortunately do no longer have enough time to review PRs, and introduce new features.

The future of the bundle is currently discussed in https://github.com/FriendsOfSymfony/FOSRestBundle/issues/2336 and on Symfony's slack under `#fosrestbundle`.

**Comment by goetas** [comment]
This is green and ready to be reviewed

**Pull request merged**
