### PR TITLE
Supporting "list" as alternative route name for "cgetAction".

### PR DESCRIPTION
**Pull request by kherge**
See #1695.

### CODE REVIEW

**Comment by kherge** [comment]
I've also considered making the actual `list` prefix configurable through the `fos_rest.routing.cget_list` setting. Maybe rename the setting to `fos_rest.routing.cget` and default it to `cget`?

I'm open to suggestions.

**Comment by kherge** [comment]
Hi @GuilhemN, please let me know if there is anything I can do to help move this along!

**Comment by lsmith77** [comment]
Generally the idea would be to have `get_users` vs. `get_user` for such route names, but not all subjects will nicely pluralize.

So this sounds like a sensible solution to me.
Maybe we should even deprecate the old behavior?

**Comment by kherge** [comment]
I believe that the original behavior should be deprecated.

The original behavior would break route generation when used without `ClassResourceInterface`.

**Comment by kherge** [comment]
Abandoning in favor of using a custom route loader.

**Pull request closed without merging**
