### PR TITLE
Backport #1370

### PR DESCRIPTION
**Pull request by Ener-Getick**
Backport #1370 to 2.0 (needed to fix the tests)

### CODE REVIEW

**Comment by xabbuh** [comment]
@Ener-Getick should then backport this to 1.8 too to minimise the gap between both versions.

**Comment by Ener-Getick** [comment]
You're right @xabbuh, i'll open an issue

**Comment by Ener-Getick** [comment]
@xabbuh I remember why I didn't do it, this is based on https://github.com/FriendsOfSymfony/FOSRestBundle/commit/05330bab029201c6a976da392f46a59ccb7d58b5 so it needs some modifications to be integrated in 1.8.

**Comment by Ener-Getick** [comment]
see https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1456

**Pull request merged**
