### PR TITLE
make it possible to define a separate fallback format for exceptions

### PR DESCRIPTION
**Pull request by lsmith77**

### CODE REVIEW

**Comment by renatomefidf** [comment]
Hello @lsmith77 

I was trying this new feature, when I setup the exception_fallback_format priorities to [json, html] it worked nice, but I was expecting to don't need any config if my request is a application/json, is there a way to configure this way?

Here is my config:

```yaml
fos_rest:
    param_fetcher_listener: false
    view:
        view_response_listener: true
    routing_loader:
        default_format: json
        include_format: false
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
```

**Comment by lsmith77** [comment]
can you paste your entire config?

a short explanation of how things work .. in case of an exception we run through the content negotiation once more since we do not know for sure if the format has been determined properly yet when the exception was thrown.

**Comment by renatomefidf** [comment]
of course, here it is:

```yaml
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ FrontendBundle , TranslateBundle ]

    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

sp_bower:
    allow_root: true
    bin: %bower_bin%
    assetic:
        enabled: false
    bundles:
        FrontendBundle: ~
        TranslateBundle: ~

# Doctrine Configuration
#doctrine:
#    dbal:
#        driver:   %database_driver%
#        host:     %database_host%
#        port:     %database_port%
#        dbname:   %database_name%
#        user:     %database_user%
#        password: %database_password%
#        charset:  UTF8
#        # if using pdo_sqlite as your database driver, add the path in parameters.yml
#        # e.g. database_path: %kernel.root_dir%/data/data.db3
#        # path:     %database_path%
#
#    orm:
#        auto_generate_proxy_classes: %kernel.debug%
#        auto_mapping: true

# Doctrine MongoDB Bundle Configuration
doctrine_mongodb:
    connections:
        default:
            server: %mongodb_connection_string%
            options: %mongodb_connection_options%
    default_database: %mongodb_database%
    document_managers:
        default:
            auto_mapping: true
            mappings:
                FOSUserBundle: ~
#                AppBundle:
#                    type: annotation
#                    dir: %kernel.root_dir%/../src/AppBundle/Document
#                    prefix: AppBundle\Document

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_rest:
    param_fetcher_listener: false
    view:
        view_response_listener: true
    routing_loader:
        default_format: json
        include_format: false
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true

services:
  kernel.event_listener.json_request_transformer:
    class: Qandidate\Common\Symfony\HttpKernel\EventListener\JsonRequestTransformerListener
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }

# FOS User Bundle for ORM
# In order to use ORM change the parameters.yml to
# fos_user_db_driver: orm
# fos_user_class: Flyers\BackendBundle\Entity\User
fos_user:
    db_driver: %fos_user_db_driver%
    firewall_name: main
    user_class: %fos_user_class%
```

**Comment by lsmith77** [comment]
it seems like right now, you do not configure the format listener at all:
http://symfony.com/doc/master/bundles/FOSRestBundle/3-listener-support.html#format-listener

**Comment by renatomefidf** [comment]
When I do this, even if I access it without accept application/json it is always returning a json.

```yaml
    format_listener:
        rules:
            - { path: '^/l10n', priorities: [json], fallback_format: html, prefer_extension: false }
```

Sorry to bother you, I'm really new in SF2.
What I want to do is:
Request header has accept application/json it need to return a json and if there is no accept I want to use the fallback wich is html.

This way I can keep my API and a common html working together!

Thank you again

**Comment by lsmith77** [comment]
In that case you should probably do something like:

```
    format_listener:
        rules:
            - { path: '^/l10n', priorities: [json, html], fallback_format: html, prefer_extension: false }
```

This means you prefer json but are also willing to serve up html in case the accept header does not allow json.

**Comment by renatomefidf** [comment]
I worked! Thank you

I was thinking that priorities was not an "exclusive" response types, but just a priority list.

Now my configuration is:
```yaml
    format_listener:
            rules:
                - { path: '^/l10n', priorities: [json, xml, html], fallback_format: json, prefer_extension: false }
                - { path: '^/', priorities: [html, json], fallback_format: html, prefer_extension: false }
```

**Pull request merged**
