### PR TITLE
Remove deprecation warning about final ExceptionListener

### PR DESCRIPTION
**Pull request by yceruto**
Replaces https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2018

### CODE REVIEW

**Comment by sarcher** [comment]
Thanks @yceruto, I have tested this so far in a Symfony 4.3 and 5.0 project and it seems to be working fine in both.

**Comment by rmikalkenas** [comment]
@Tobion when we could expect expect this merge request to be merged?

**Comment by MaSpeng** [comment]
@maxhelias since Symfony 4.4 and 5.0 has been released, how about merging this one and creating a new release?

**Comment by maxhelias** [comment]
@MaSpeng, I'm sorry to tell you that I have no rights 😅 
For information, the people having right to the current repository have their approval display in green

**Comment by rmikalkenas** [comment]
Ping @Tobion

**Comment by XWB** [comment]
Thank you @yceruto

**Pull request merged**
