### PR TITLE
remove the deprecated automatic route feature

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by Tobion** [comment]
Looks like you forgot the stuff from #2157

**Comment by xabbuh** [comment]
@Tobion I actually merged this PR a few hours ago. I have no idea why GitHub only marked it as merged now.

**Comment by Tobion** [comment]
I'll create a new pr then.

**Comment by xabbuh** [comment]
Sorry, I didn't see your comment before. In the meantime I merged #2159.

**Comment by nuvolapl** [comment]
But why? :( that was (almost) the killer feature

**Comment by xabbuh** [comment]
@nuvolapl see #1954 for more information

**Pull request merged**
