### PR TITLE
Fixed SF 6.1 and SF 6.2 deprecations

### PR DESCRIPTION
**Pull request by deluxetom**
Screenshot 2022-11-29 at 3 10 39 AM

* Fixes SF 6.1 deprecations
* Fixes SF 6.2 deprecations
* Fixed github action deprecations

### CODE REVIEW

**Comment by deluxetom** [comment]
@goetas it took me quite a while to fix all those deprecations, hoping to get this merged quickly since SF 6.2 is around the corner and this bundle isn't even compatible with SF 6.1 yet

let me know if you need any changes, thank you!

**Review by boskos-q — APPROVED** [review]

**Review by icvij — APPROVED** [review]

**Comment by deluxetom** [comment]
@goetas friendly bump :) let me know if I can help

**Comment by deluxetom** [comment]
@goetas I've been using my version on production for a few weeks now and its been working well, if that helps getting this PR merged

**Comment by goetas** [comment]
thanks and sorry for the delay

**Pull request merged**
