### PR TITLE
Version annotation exists only in branch 2.0

### PR DESCRIPTION
**Pull request by hpatoio**
Let's remove this part from 1.8 doc

### CODE REVIEW

**Comment by stof** [comment]
note for maintainers: this commit should be reverted in the master branch after merging 1.8 into master

**Comment by xabbuh** [comment]
@lsmith77 @Ener-Getick I wonder if we should not rather backport #1182 to the `1.8` branch instead. The PR looks fully backwards compatible to me. What do you think?

**Comment by lsmith77** [comment]
I am fine with not backporting the version annotation

**Comment by xabbuh** [comment]
Thank you @hpatoio.

**Pull request merged**
