### PR TITLE
Provide the formats as parameter to be reusable in other bundles

### PR DESCRIPTION
**Pull request by alexander-schranz**
For creating the FOSRestRoutingBundle I need a way to access the formats of the FOSRestBundle.

### CODE REVIEW

**Comment by xabbuh** [comment]
Thanks for the PR! I wonder if it could be worth to add a service providing access to the configured formats instead. Using parameters always comes with the drawback that it's nearly impossible to properly deprecate them.

**Comment by alexander-schranz** [comment]
@xabbuh sure I can create a service for it and use expression to access inject the formats e.g.:

```xml
<argument type="expression">service('fos_rest.formats_provider').getFormat()</argument>
```

Where do you want me to place it? How you would name it `FormatsProvider`?

**Comment by xabbuh** [comment]
👍 for `FormatsProvider`, and I think 2.8 is a good target to not introduce new features in 3.0 that are not present in 2.8.

**Comment by alexander-schranz** [comment]
@xabbuh ready for review!

**Comment by alexander-schranz** [comment]
Ok we did solve the issue using a compiler pass when the FOSRestBundle is available and read the formats from the ViewHandler service.

**Pull request closed without merging**
