### PR TITLE
Use twig as templating engine when available

### PR DESCRIPTION
**Pull request by alexander-schranz**
Currently if `symfony/templating` is not installed the following error could happen:

> An instance of Symfony\Component\Templating\EngineInterface must be injected in FOS\RestBundle\View\ViewHandler to render templates.

thats because templating is set as default value. If templating is not available but twig it should use twig instead.

### CODE REVIEW

**Comment by Tobion** [comment]
#2022 does not fix this right?

**Comment by alexander-schranz** [comment]
@Tobion Thx for the review, you are right,  this currently overwrites it.
And no #2022 does not fix it as it still defaults to `templating` currently at https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/DependencyInjection/Configuration.php#L140 and there is no fallback to twig implemented.

**Comment by XWB** [comment]
@Tobion No https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2022 does not fix the issue. The problem is that FOSRestBundle always worked without any configuration because EngineInterface was always injected into `ViewHandler`. After https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2022 got merged I got the following error:

> An instance of Symfony\Component\Templating\EngineInterface must be injected in FOS\RestBundle\View\ViewHandler to render templates.

I fixed it by creating `fos_rest.yaml` and configuring the templating engine:

```yaml
fos_rest:
    service:
        templating: twig
```

In my opinion FOSRestBundle should work without configuration, like it did before.

**Comment by alexander-schranz** [comment]
@XWB yes this should be fixed with this PR. Need to check how I can pack this into a test case.

**Comment by Tobion** [comment]
Thanks @alexander-schranz

**Pull request merged**
