### PR TITLE
[docs] Symfony 4.0 bundle registration

### PR DESCRIPTION
**Pull request by Idziak**
In Symfony 4.0 there are a new bundle registration procedure

### CODE REVIEW

**Comment by xabbuh** [comment]
If you are using Symfony Flex, the `config/bundles.php` file does not have to be changed manually. I would omit that part and just reword the existing paragraph to explain that the step is only necessary if you do not use Flex.

**Comment by GuilhemN** [comment]
I agree with @xabbuh :+1:

**Comment by GuilhemN** [comment]
I added a ``caution`` for users not using Flex. Does it look good to you?

**Comment by GuilhemN** [comment]
We may also merge https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1743 directly to avoid merge conflicts.

**Comment by GuilhemN** [comment]
Thank you @Idziak!

**Pull request merged**
