### PR TITLE
Corrected an exception's typo

### PR DESCRIPTION
**Pull request by Rewieer**

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1:

**Comment by Ener-Getick** [comment]
Should be merged in 1.8 i guess ? 👍

**Comment by Rewieer** [comment]
This is my first commit, I don't know much about github yet. So.. Am I supposed to do something or is everything ok ?

**Comment by Ener-Getick** [comment]
Everything's ok, i'm just not near a computer to merge this for now 😉

**Comment by xabbuh** [comment]
Thank you @Rewieer. FYI, I have merged your PR into the `2.0` branch as this was the version where we introduced the `ControllerTrait`. From there everything will be merged up to the `master` branch soon.

**Pull request closed without merging**
