### PR TITLE
Fix Symfony 4.4 compatibility

### PR DESCRIPTION
**Pull request by yceruto**
Fix https://github.com/FriendsOfSymfony/FOSRestBundle/issues/2031

### CODE REVIEW

**Comment by XWB** [comment]
Just one unit test failure:

> PHP Fatal error:  Declaration of FOS\RestBundle\Tests\Functional\ExceptionListenerTest::tearDown() must be compatible with Symfony\Bundle\FrameworkBundle\Test\WebTestCase::tearDown(): void in /home/travis/build/FriendsOfSymfony/FOSRestBundle/Tests/Functional/ExceptionListenerTest.php on line 51

**Comment by yceruto** [comment]
To be continue...

**Comment by maxhelias** [comment]
Thanks @yceruto for taking care of this. #2032 can be closed when it is merged

**Comment by yceruto** [comment]
The compatibility issue with 4.4 was solved and I also fixed some related to 5.0, but making this bundle compatible completely with Symfony 5.0 and keep BC may take more time than I can spend on it. So, I'd suggest do that in another iteration (or feel free to take over).

The big problem is related to the exception listener + error response layer. That layer might require a full refactor to integrate the new one added in 4.4 or a new way to hook into it. Doing that and keeping BC is too hard for me considering I'm not an expert on this bundle.

Cheers!

**Comment by sarcher** [comment]
Maybe it is worth moving to a 3.x that supports Symfony 5+ and keeping 2.x as it is? That sounds like it would be more simple to maintain, rather than having a bunch of spidery code that tries to do everything.

I also don't understand the full intent of the exception and error response layer here so when I tried to dig into it, I didn't get very far.

**Comment by XWB** [comment]
@yceruto Would you be able to fix the last unit test as well?

**Comment by yceruto** [comment]
@XWB I don't know, at this moment there is a blocker here https://github.com/symfony/symfony/issues/34731, but later it might require a full refactor to integrate the new error renderer system. Note that in Symfony 5.0 there is no error templates in TwigBundle.

It is likely that splitting supported versions is best https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2036#issuecomment-560474034.

**Comment by seddighi78** [comment]
have I downgraded Symfony to 4.3 for the fix problem?

**Comment by Toilal** [comment]
I'm currently running this branch with Symfony 4.4, with seems to run nicely.

Change composer.json with those settings :

```json
    "require": {
        "friendsofsymfony/rest-bundle": "dev-error_listener",
    },
    "repositories": [
      {
        "type": "git",
        "url": "https://github.com/yceruto/FOSRestBundle.git"
      }
    ],
```

**Comment by seddighi78** [comment]
@Toilal Thanks a lot.

**Comment by pamil** [comment]
@yceruto if @Toilal is right, then rebasing this branch to the lates master and rerunning the build should make it passing :)

**Comment by XWB** [comment]
@yceruto Can you fix the remaining test as well?

**Comment by yceruto** [comment]
@XWB the remaining tests are related to Symfony 5.0 compatibility which we are adv should be done in another branch & major release.

This PR is ready for 4.4 compatibility and remove some deprecations.

**Comment by lsmith77** [comment]
or in other words .. it doesn't seem feasible to have a single branch that works for 5.0 and 4.4

**Comment by yceruto** [comment]
@lsmith77 right! too many ugly workarounds are required to achieve this, it is not worth it IMO.

**Comment by XWB** [comment]
In that case we should revert https://github.com/FriendsOfSymfony/FOSRestBundle/commit/72e11ead5e5e47187a0d8157e0f2ac78d5f8ff4d and remove the Symfony 5 hacks from this PR.

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2049

**Comment by chq81** [comment]
@yceruto Are there any plans yet to provide a 3.x version with symfony 5 support? If I find time I will help out.

**Comment by XWB** [comment]
@yceruto Would you be able to remove the Symfony 5 hacks from this PR?

**Comment by yceruto** [comment]
This one https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2049 is required to have the tests in green here.

**Comment by XWB** [comment]
@yceruto Thank you. I've just merged https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2049. Can yo rebase so we are sure all tests are green?

**Comment by yceruto** [comment]
@XWB done :)

**Comment by XWB** [comment]
Perfect, thank you :)

**Comment by chq81** [comment]
@yceruto Thanks. Will this version be tagged?

**Comment by JohnnySteunwijzer** [comment]
I'm still getting `Argument 1 passed to FOS\RestBundle\Controller\ExceptionController::getStatusCode() must be an instance of Exception, instance of TypeError given` What are the steps to fix this?

**Comment by seddighi78** [comment]
@JohnnySteunwijzer 

1. Change `composer.json ` and update the fos-rest: 
```
"require": {
        "friendsofsymfony/rest-bundle": "dev-error_listener",
    },
```
and add this lines to file
```
"repositories": [
      {
        "type": "git",
        "url": "https://github.com/yceruto/FOSRestBundle.git"
      }
    ],
```
2. Run `composer update` to update fos-rest
3. Change `fos-rest.yaml` and set exception to enable:
```
fos_rest:
    exception:
        enabled: true
```
4. Run `php bin/console cache:clear` for clear the cache
5. Done

**Comment by derWebdesigner** [comment]
@seddighi78 Does this work with Symfony 5 as well or only 4.4?

**Comment by blackarcanis** [comment]
@seddighi78 The "dev-error_listener" is not existing anymore, it has already been deleted...

So now we are waiting a tag version for this merge on the master, right ?

**Comment by seddighi78** [comment]
oh, it's so bad
@xabbuh Please tag this version maybe this is an emergency.
thanks

**Comment by seddighi78** [comment]
@blackarcanis yes you have to use master version this branch is merged with `master`

**Comment by yceruto** [comment]
I've restore this branch in the meantime, but you should use the `master` branch of the owner repo instead until the new tag is created.

**Comment by derWebdesigner** [comment]
@yceruto Thank you very much Yonel! This branch is only working with Symfony 4.4 though or with 5.0 as well?

**Comment by yceruto** [comment]
This branch is only working with Symfony 4.4.

**Comment by geerteltink** [comment]
@XWB can you tag a new release with this fix please?

**Comment by XWB** [comment]
Unfortunately there are still several deprecation: https://github.com/FriendsOfSymfony/FOSRestBundle/issues/2059

I think it should be fixed before tagging version 2.7

**Comment by xabbuh** [comment]
I just tagged 2.7.0

**Comment by vincentjdc** [comment]
When I've an error in my php code (let say a missing semicolon), I get a HTML 500 error :

> Oops! An Error Occurred
> The server returned a "500 Internal Server Error".
> Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

In the logs I can see the initial error (the missing semicolon) and after the following error :

> [2020-02-12 17:20:24] php.CRITICAL: Uncaught Error: Argument 1 passed to FOS\RestBundle\Controller\ExceptionController::getStatusCode() must be an instance of Exception, instance of Symfony\Component\ErrorHandler\Error\UndefinedMethodError given, called in /var/www/vendor/friendsofsymfony/rest-bundle/Controller/ExceptionController.php on line 68 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to FOS\\RestBundle\\Controller\\ExceptionController::getStatusCode() must be an instance of Exception, instance of Symfony\\Component\\ErrorHandler\\Error\\UndefinedMethodError given, called in /var/www/vendor/friendsofsymfony/rest-bundle/Controller/ExceptionController.php on line 68 at /var/www/vendor/friendsofsymfony/rest-bundle/Controller/ExceptionController.php:102)"} 

I expect FOSRestBundle to generate a json error.

Here is my conf :
- Symfony 4.4.4
- FOSRestBundle 2.7.0
- fos_rest.yaml (full) :
```yaml
fos_rest:
  disable_csrf_role: IS_AUTHENTICATED_FULLY
  param_fetcher_listener: true
  view:
    view_response_listener: true
  format_listener:
    rules:
      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
  exception:
    enabled: true
    exception_controller: 'fos_rest.exception.controller:showAction'
    codes:
      Doctrine\ORM\EntityNotFoundException: 404
      Symfony\Component\HttpKernel\Exception\BadRequestHttpException:  400
      Symfony\Component\Routing\Exception\ResourceNotFoundException: 404
  serializer:
      groups: [Default]
```
- framework.yaml (a part only)
```yaml
framework:
    error_controller: null
```

any idea ?

**Comment by xabbuh** [comment]
Can you please create a new issue and provide a small application that allows to reproduce it?

**Comment by vincentjdc** [comment]
> Can you please create a new issue and provide a small application that allows to reproduce it?

Done :) https://github.com/FriendsOfSymfony/FOSRestBundle/issues/2092

**Comment by faresk93** [comment]
I'm still getting the error:
`Argument 1 passed to FOS\RestBundle\Controller\ExceptionController::getStatusCode() must be an instance of Exception, instance of TypeError given, called in C:\Users\fkhiary\Desktop\SagemCom\Portail-2g-Backend\vendor\friendsofsymfony\rest-bundle\Controller\ExceptionController.php on line 66`

Any news about this issue please ?

**Comment by xabbuh** [comment]
see #2092/#2093

**Pull request merged**
