### PR TITLE
Remove default value for ZONE_ATTRIBUTE in Request

### PR DESCRIPTION
**Pull request by spolischook**

### CODE REVIEW

**Comment by xabbuh** [comment]
Can you explain which issue this is going to solve and please also add a test case for it?

**Comment by spolischook** [comment]
@xabbuh this one https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1402 . Is it make sense? or I made something wrong?
I have non rest routes where I throw exception and Fos Rest Exception listener run for all resources, so I have issue with template.

Should I set ZONE_ATTRIBUTE parameter to false in non rest routes? and how?

**Comment by spolischook** [comment]
Should I configure ZoneMatcherListener somehow?

**Comment by xabbuh** [comment]
Did you configure any REST zones?

**Comment by spolischook** [comment]
I guess no, did we have doc about it?

**Comment by spolischook** [comment]
Found it https://symfony.com/doc/master/bundles/FOSRestBundle/3-listener-support.html#zone-listener

**Comment by xabbuh** [comment]
IIRC the attribute will only ever be set if any zones are configured. That's why we assume that the default value is `true` to cover the case where no zones have been configured and all listeners should be enabled all the time.

**Comment by spolischook** [comment]
Yea it make sense, but it disappointing that twig cant find the template for the exception.
I guess that twig exception could be catcher and native page with exception should be shown.
But I'm already configured zones, so my issues is resolved.
Maybe someone have time and desire to fix this behavior.

**Comment by xabbuh** [comment]
> but it disappointing that twig cant find the template for the exception.

Can you clarify that a bit? I am not sure I completely understand what behaviour you are talking about.

**Pull request closed without merging**
