### PR TITLE
Add versionadded directive for setTemplateData

### PR DESCRIPTION
**Pull request by xelaris**
See also https://github.com/symfony/symfony-docs/issues/5151#issuecomment-89974092.

### CODE REVIEW

**Comment by lsmith77** [comment]
@schmittjoh this is what I mean with scrutinizer failing.

**Comment by schmittjoh** [comment]
Yeah, this is because PHP7 does not yet have the xdebug extension, and cannot generated code coverage. You see this in the nightly job here: https://travis-ci.org/FriendsOfSymfony/FOSRestBundle/jobs/57321300#L272

The only solution at the moment is to not try to upload code coverage if a job cannot generate it.

**Comment by lsmith77** [comment]
@schmittjoh oh .. didn't realize someone has added php7 already to the builds. is there a work around to prevent breaking CI just because we have php7?

**Comment by xabbuh** [comment]
@lsmith77 you can have a look at #1005 (it's already merged, just in case you need it somewhere else)

**Pull request merged**
