### PR TITLE
CS backport

### PR DESCRIPTION
**Pull request by Soullivaneuh**
As discussed on https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1166#issuecomment-146811495.

> I suggest to merge 1.7 on master just after the CS PR and ignore modification (because CS is already fixed on master). Then you will able to continue merges later.

### CODE REVIEW

**Comment by lsmith77** [comment]
maybe I didn't understand the approach .. but it seems there are still CS violations left to fix.

**Comment by Soullivaneuh** [comment]
Strange. Will take a look.

**Comment by Soullivaneuh** [comment]
Seems StyleCI has extra check that PHP-CS-Fixer could not handle.

Will manually fix it.

**Comment by Soullivaneuh** [comment]
@lsmith77 CS fixed.

**Pull request merged**
