### PR TITLE
[WIP] Support Using Directories as a Routing Resource

### PR DESCRIPTION
**Pull request by ChadSikorra**
This change lets you import all controllers in a directory using a syntax like `@AcmeDemoBundle/Controller/Api`. I recently wanted to do this in a project and realized it wasn't currently possible. This fixes https://github.com/FriendsOfSymfony/FOSRestBundle/issues/189

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
:+1: 

What is missing to get this PR merged?

**Comment by lsmith77** [comment]
@Soullivaneuh see also https://github.com/FriendsOfSymfony/FOSRestBundle/pull/798 .. someone needs to go through the comments in each of these PRs and clean things up .. feel free to do this in a new PR .. @xabbuh also seems interested

**Comment by ChadSikorra** [comment]
Sorry, this kinda fell off my radar. Due to a recent job change and other things I'm not sure I'll find the time to clean this up again. If someone wants to resubmit this on a different PR please do! I think the only real issue left on this (as I remember it) was fleshing out the tests.

**Comment by xabbuh** [comment]
closing here in favour of #1339

**Pull request closed without merging**
