### PR TITLE
Fix broken @ViewAnnotation with sensio/framework-extra-bundle >=3.0.13

### PR DESCRIPTION
**Pull request by iTechDhaval**
Add kernel.controller event to setup default owner for template which got updated in sensio/framework-extra-bundle >=3.0.13

When we are using @View Annotation with sensio/framework-extra-bundle >=3.0.13, we are getting below exception message from ViewResponseListener.php.

```
Warning: ReflectionObject::__construct() expects parameter 1 to be object, null given
    at n/a
        in /vendor/friendsofsymfony/rest-bundle/EventListener/ViewResponseListener.php line 179
    at Symfony\Component\Debug\ErrorHandler->handleError('2', 'ReflectionObject::__construct() expects parameter 1 to be object, null given', '/vendor/friendsofsymfony/rest-bundle/EventListener/ViewResponseListener.php', '179', array('template' => object(View), 'controller' => null, 'action' => null, 'arguments' => array()))
        in  line 
    at ReflectionObject->__construct(null)
        in /vendor/friendsofsymfony/rest-bundle/EventListener/ViewResponseListener.php line 179
    at FOS\RestBundle\EventListener\ViewResponseListener->getDefaultVars(object(View), null, null)
        in /vendor/friendsofsymfony/rest-bundle/EventListener/ViewResponseListener.php line 116
    at FOS\RestBundle\EventListener\ViewResponseListener->onKernelView(object(GetResponseForControllerResultEvent), 'kernel.view', object(TraceableEventDispatcher))
        in  line 
    at call_user_func(array(object(ViewResponseListener), 'onKernelView'), object(GetResponseForControllerResultEvent), 'kernel.view', object(TraceableEventDispatcher))
        in /vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php line 61
    at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(GetResponseForControllerResultEvent), 'kernel.view', object(ContainerAwareEventDispatcher))
        in  line 
    at call_user_func(object(WrappedListener), object(GetResponseForControllerResultEvent), 'kernel.view', object(ContainerAwareEventDispatcher))
        in /var/cache/dev/classes.php line 1751
    at Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(array(object(WrappedListener)), 'kernel.view', object(GetResponseForControllerResultEvent))
        in /var/cache/dev/classes.php line 1669
    at Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.view', object(GetResponseForControllerResultEvent))
        in /vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php line 132
    at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.view', object(GetResponseForControllerResultEvent))
        in /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 144
    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), '1')
        in /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 62
    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), '1', true)
        in /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 169
    at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
        in /web/app_dev.php line 30
    at require('/web/app_dev.php')
        in /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/config/router_dev.php line 40
```

We are getting this error because ViewResponseListener.php trying to set default variables at [line#91](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/EventListener/ViewResponseListener.php#L90) and not able to get template owner controller.

Solution #1:
use `@View(populateDefaultVars=false)` in annotation which seems to be wrong.

Solution #2:
Add new subscriber for event `kernel.controller` in  ViewResponseListener.php  to setup owner as it has been updated in sensio/framework-extra-bundle >=3.0.13 to define owner of template.

### CODE REVIEW

**Comment by Ener-Getick** [comment]
This should work...
Did you disable the SensioFrameworkBundle ``@Template`` annotation ?

**Comment by iTechDhaval** [comment]
I have setup my config.yml
```yaml
sensio_framework_extra:
    view:    { annotations: false }
```

are you referring to it?

**Comment by Ener-Getick** [comment]
Yeah you have to enable it. I think we should throw an exception when it isn't the case...

**Comment by sloba88** [comment]
But it tells me that I need to disable it?

So how do I use @Template annotations together with FosRest?

Now I get error that I should disable view annotations
```
You need to disable the view annotations in SensioFrameworkExtraBundle when using the FOSRestBundle View Response listener. Add "view: { annotations: false }" to the sensio_framework_extra: section of your config.yml
```

**Comment by Ener-Getick** [comment]
@sloba88 it has to be disabled on 1.* and enabled on 2.0

**Pull request closed without merging**
