### PR TITLE
make classes final

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by alterphp** [comment]
Hi @xabbuh !

Final class breaks with `ocramius/proxy-manager`.

See :

```
php bin/console cache:clear -vv

In InvalidProxiedClassException.php line 26:
                                                                                                      
  [ProxyManager\Exception\InvalidProxiedClassException]                                               
  Provided class "FOS\RestBundle\Serializer\SymfonySerializerAdapter" is final and cannot be proxied  
                                                                                                      

Exception trace:
  at /var/www/symfony/vendor/ocramius/proxy-manager/src/ProxyManager/Exception/InvalidProxiedClassException.php:26
 ProxyManager\Exception\InvalidProxiedClassException::finalClassNotSupported() at /var/www/symfony/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/Assertion/CanProxyAssertion.php:54
 ProxyManager\ProxyGenerator\Assertion\CanProxyAssertion::isNotFinal() at /var/www/symfony/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/Assertion/CanProxyAssertion.php:38
 ProxyManager\ProxyGenerator\Assertion\CanProxyAssertion::assertClassCanBeProxied() at /var/www/symfony/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/LazyLoadingValueHolderGenerator.php:56
 ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator->generate() at /var/www/symfony/vendor/symfony/proxy-manager-bridge/LazyProxy/PhpDumper/LazyLoadingValueHolderGenerator.php:35
 Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\LazyLoadingValueHolderGenerator->generate() at /var/www/symfony/vendor/symfony/proxy-manager-bridge/LazyProxy/PhpDumper/ProxyDumper.php:126
 Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\ProxyDumper->generateProxyClass() at /var/www/symfony/vendor/symfony/proxy-manager-bridge/LazyProxy/PhpDumper/ProxyDumper.php:83
 Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\ProxyDumper->getProxyCode() at /var/www/symfony/vendor/symfony/dependency-injection/Dumper/PhpDumper.php:512
 Symfony\Component\DependencyInjection\Dumper\PhpDumper->generateProxyClasses() at /var/www/symfony/vendor/symfony/dependency-injection/Dumper/PhpDumper.php:228
 Symfony\Component\DependencyInjection\Dumper\PhpDumper->dump() at /var/www/symfony/vendor/symfony/http-kernel/Kernel.php:718
 Symfony\Component\HttpKernel\Kernel->dumpContainer() at /var/www/symfony/vendor/symfony/http-kernel/Kernel.php:555
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /var/www/symfony/vendor/symfony/http-kernel/Kernel.php:126
 Symfony\Component\HttpKernel\Kernel->boot() at /var/www/symfony/vendor/symfony/framework-bundle/Console/Application.php:169
 Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() at /var/www/symfony/vendor/symfony/framework-bundle/Console/Application.php:75
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/symfony/vendor/symfony/console/Application.php:140
 Symfony\Component\Console\Application->run() at /var/www/symfony/bin/console:42
```

**Comment by xabbuh** [comment]
@alterphp Do you have an idea why the proxy manager tries to deal with the `SymfonySerializerAdapter` class? This doesn't seem really obvious to me.

**Comment by alterphp** [comment]
Not yet, I don't really understand what it does, I know I use it for services lazy loading.

**Comment by alterphp** [comment]
`XxxxSerializerAdapter` seem to be the two services that are marked as lazy in the DI config

**Comment by xabbuh** [comment]
Oh I missed that the service is declared as private. I am going to look into if that's necessary orn ot.

**Comment by xabbuh** [comment]
see #2122

**Pull request merged**
