### PR TITLE
#1569: Added suffix "Action" for getUsers() method as it is required …

### LINKED ISSUE #1569: It is not possible to define route manually without "Action" suffix in controller method name
Actually, it is normal behaviour for `RestActionReader`, but [**documentation**](http://symfony.com/doc/current/bundles/FOSRestBundle/7-manual-route-definition.html#method-name-prefix) in this case confuses developers to use manual definition of routes. Example demonstrates following snippet: `public function getUsers() { /** */ }`, but without `Action` suffix it will not work according to this condition [Routing/Loader/Reader/RestActionReader.php#L430](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Routing/Loader/Reader/RestActionReader.php#L430)

How to update documentation for this component?

### PR DESCRIPTION
**Pull request by warlock39**
…precondition to define route manually

Fixes #1569

### CODE REVIEW

**Comment by Ener-Getick** [comment]
Why this change? The Action prefix is not required for manual routing it is only for automatic routing.

**Comment by warlock39** [comment]
@Ener-Getick , thank for your feedback.

According to description of referenced issue: #1569 , the condition in [Routing/Loader/Reader/RestActionReader.php#L430](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Routing/Loader/Reader/RestActionReader.php#L430) filters any class methods without `Action` suffix. So there are two options to get manual routing work:

1. Register additional routing resource (example: `resource: '@AppBundle/Controller/'` with `type: annotation`) in `routing.yml`
2. Add `Action` suffix to method name with custom route annotation

[Documentation](http://symfony.com/doc/master/bundles/FOSRestBundle/7-manual-route-definition.html) says nothing about it.
If i overlooked something, please let me know.

**Comment by Ener-Getick** [comment]
Ok got it.
I have to look deeper into the implementation but imo we should instead remove this restriction when using custom routes.

**Comment by lsmith77** [comment]
I am not 100% sure but I think this restriction was for security reasons.

**Comment by Ener-Getick** [comment]
@lsmith77 I understand for automatic routes (eg we don't want all methods to be converted to routes)
```
// should not be converted to a route
public function getUser(): UserInterface
{
}
```

but if the user explicitly requires a route what security problems could it cause?
```
/**
 * @Get('/user')
 */
public function getUser(): UserInterface
{
}

**Comment by lsmith77** [comment]
that should be fine indeed.

**Comment by Ener-Getick** [comment]
Let's merge this for now :)

**Pull request merged**
