### PR TITLE
Minor typo correction

### PR DESCRIPTION
**Pull request by toby-griffiths**

### CODE REVIEW

**Comment by Ener-Getick** [comment]
Could you rebase your changes on 2.0 please?

**Comment by xabbuh** [comment]
Thank you @toby-griffiths! I rebased your changes while merging them into the `2.0` branch (from there we will merge them up to the `master` branch).

**Comment by Ener-Getick** [comment]
Thanks @xabbuh !

**Comment by toby-griffiths** [comment]
@xabbuh Thank you.

**Pull request closed without merging**
