### PR TITLE
merge branch 1.7 into 1.8

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by xabbuh** [comment]
@Ener-Getick I do not see a problem. Tests run successfully.

**Comment by Ener-Getick** [comment]
@xabbuh yeah it's just that I can't merge branches on my phone :x

**Comment by Ener-Getick** [comment]
Thank you @xabbuh ☺

**Comment by xabbuh** [comment]
Oh then I misunderstood your problem. :)

**Pull request merged**
