### PR TITLE
[WIP] Import routes from a controller directory

### PR DESCRIPTION
**Pull request by jorgebg**
Import routes from a controller directory #796

### CODE REVIEW

**Comment by xabbuh** [comment]
What is the state here? Do you still work on it @jorgebg?

**Comment by lsmith77** [comment]
btw there is also https://github.com/FriendsOfSymfony/FOSRestBundle/pull/443

@xabbuh I would say just take it over :)

**Comment by JHGitty** [comment]
ping @xabbuh Do you like to take it over? #798 (this) and #443 don't have time for it.

**Comment by Ener-Getick** [comment]
:+1: would be great but IMO we should create a ``RestDirectoryLoader`` instead of using the ``RestRouteLoader``.
Maybe even create a specific type ``rest_directory`` to simplify the new loader (but this second idea is not really user friendly...).

**Comment by xabbuh** [comment]
@JHGitty @Ener-Getick I'll look into this this week.

**Comment by xabbuh** [comment]
closing here in favour of #1339

**Pull request closed without merging**
