### PR TITLE
handle throwable

### PR DESCRIPTION
**Pull request by fprochazka**

### CODE REVIEW

**Comment by Ener-Getick** [comment]
``1.7`` is not really supported anymore... so i think this should only be applied on 1.8.
WDYT @xabbuh @lsmith77 ?

**Comment by xabbuh** [comment]
To me this is a bug fix and should be merged in 1.7 as this is currently the only stable version we have.

@fprochazka Can revert the change to the docs here?

**Comment by fprochazka** [comment]
Done :)

**Comment by xabbuh** [comment]
:+1:

**Comment by Ener-Getick** [comment]
fine for me then :+1:

**Comment by Ener-Getick** [comment]
Thank you @fprochazka

**Comment by fprochazka** [comment]
@Ener-Getick thank you too!

**Pull request merged**
