### PR TITLE
Backport/pr 1314

### PR DESCRIPTION
**Pull request by Ma27**
@xabbuh wanted me to backport the feature implemented in #1314 into the 1.8 branch to provide at least parts of the feature in older versions, so the first two commits of that feature containing no BC breaks are cherry-picked into this branch.

for more information please see the discussion in the actual PR for 2.0

### CODE REVIEW

**Comment by Ener-Getick** [comment]
I think that's confusing if they aren't supported by the router.

**Comment by Ma27** [comment]
I assumed that I should import all the changes that don't contain bc (annotations only). Thewhole router changes are a BCbreak.

Von meinem iPhone gesendet

**Comment by Ener-Getick** [comment]
No only for lock

**Comment by Ma27** [comment]
actually not: the fallback chosen for controller actions is "PATCH".

now imagine you have any controller methods like this:

``` php
public function copyUserAction() {}
public function mkcolUserAction() {}
public function *UserAction() {}
```

Then everyone expects in the 1.x release to have "PATCH" as fallback. With our change we introduce new http methods and then the default is not patch anymore, but MKCOL/COPY and that's definetly a BC break.

**Comment by lsmith77** [comment]
but you opened the PR again on master?

**Comment by Ma27** [comment]
embarrasing... could you please do the whole stuff with the backport if you still wish to have it (I assume that the missing router feature is a :-1: for this feature)...

**Comment by xabbuh** [comment]
@Ener-Getick @lsmith77 I think we can backport only the annotation related changes to 1.8. What do you think?

**Comment by Ener-Getick** [comment]
What do you mean ? I didn't understand your sentence :x

**Comment by xabbuh** [comment]
@Ener-Getick Sorry if that wasn't clear. I meant to backport the support for the new annotations to 1.8 and trigger deprecations if the method name prefixes whose behaviour will change with 2.0 are used. I prepare a pull request.

**Comment by Ener-Getick** [comment]
Ah ok fine for me :+1:

**Pull request closed without merging**
