### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by dnagirl**
fix help document links.

### CODE REVIEW

**Comment by xabbuh** [comment]
@dnagirl The documentation recently changed to the reStructuredText markup so that it can be rendered on symfony.com. The syntax you used for the links is Markdown which won't be parsed correctly by Sphinx (the build tool for rst docs).

**Comment by xabbuh** [comment]
@javiereguiluz Is there a schedule for when the docs for FOSRestBundle and FOSUserBundle will be available on symfony.com?

**Comment by dnagirl** [comment]
@xabbuh, I used the format described here: http://sphinx-doc.org/rest.html#hyperlinks  That's not correct?

In any event, is there a format that will work for both Symfony.com and github? Those broken links are annoying.

**Comment by xabbuh** [comment]
@dnagirl The linked format should only be used for external links. The reason is that the referenced document won't be validated when used for internal documents (opposed to what is done when using the `doc` or `ref` roles).

I'm afraid that there is nothing that could be done for now. Hopefully, the docs will be rendered soon on symfony.com so that the link can be updated in the readme file.

**Pull request closed without merging**
