### PR TITLE
Use SplObjectStorage instead of spl_object_hash

### PR DESCRIPTION
**Pull request by Ener-Getick**
See [this benchmark](http://technosophos.com/2009/05/29/set-objects-php-arrays-vs-splobjectstorage.html)

### CODE REVIEW

**Comment by xabbuh** [comment]
I am 👍 for the change, but I do not think that this counts as a bug fix and so should be merged into 1.8 instead.

**Comment by mvrhov** [comment]
in php 7 the speed difference is it's not that drastic anymore, spl is 50% faster in TTF
and uses 50% less memory.

Whats more interesting is that the test below was run on i7 6700. And the author run it on Core2Duo. 7 generations and only ~33% difference.

```
SplObjectStorage:
Time to fill: 0.063576936722.
Time to check: 0.079049000000.
Memory: 15121864

Arrays:
Time to fill: 0.135654926300.
Time to check: 0.055525000000.
Memory: 30318672
```

**Comment by stof** [comment]
There is a big difference here though: you keep a reference to the Request object, which is not released at the end of the request. Sso this will leak (even more) memory when handling several requests with the same kernel (which can happen in tests, or when using Symfony in php-pm for instance).
Note that the current code already leaks the params, but the new code also forces to leak the Request object and everything it contains.

**Comment by Ener-Getick** [comment]
You're right @stof, maybe we should add an event listener on kernel.request_finished to release memory what do you think?

**Comment by Ener-Getick** [comment]
@stof in fact the memory leak won't be resolved entirely just by using a hash to represent the request, the parameters will still be preserved.
So IMO the event listener is the best solution we have.

**Comment by Ener-Getick** [comment]
I close this for now (it can reported to 2.1 or later).

**Pull request closed without merging**
