### PR TITLE
fix symfony/security constraint

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by lsmith77** [comment]
heh .. fun little typo!

**Comment by stof** [comment]
would it be possible to depend on the security subcomponents instead of the full security component ?

**Comment by lsmith77** [comment]
@stof sure .. someone just needs to figure out which one exactly we need :)

**Comment by stof** [comment]
@lsmith77 look for any usage of the security classes in the bundle, and look at which namespace they come from :smile:

**Comment by xabbuh** [comment]
If you want to I can look for the actual dependencies later on today. Otherwise, if found this to be done fast, feel free to close here and do the split in a separate PR. :)

**Comment by stof** [comment]
From a quick github search, only ``security-core`` is needed: https://github.com/FriendsOfSymfony/FOSRestBundle/search?utf8=%E2%9C%93&q=Security

**Pull request merged**
