### PR TITLE
Fixed bug for PHP 8

### PR DESCRIPTION
**Pull request by Victor-Truhanovich**
Attempted to call an undefined method named "isBuiltin" of class "ReflectionUnionType".

### CODE REVIEW

**Comment by xabbuh** [comment]
Can you please add a test case that would fail without this change?

**Comment by Victor-Truhanovich** [comment]
```
/**
 * @Rest\Route("accounts")
 */
class AccountController extends AbstractFOSRestController implements ApiControllerInterface
{
    /**
     * @Rest\Get("/{id}", requirements={"id"="\d+"})
     *
     * @param Account|EntityInterface $account
     *
     * @return View
     */
    public function read(Account|EntityInterface $account): View
    {
        return $this->accountResponseManager->create($account);
    }
}
```

**Comment by Victor-Truhanovich** [comment]
> Can you please add a test case that would fail without this change?

Sorry, I added tests for my code, but I never got an answer from you

**Review by xabbuh — APPROVED** [review]

**Comment by xabbuh** [comment]
Thank you @Viktor-Truhanovich.

**Pull request merged**
