### PR TITLE
remove the inflector classes

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by W0rma** [comment]
@xabbuh Can the `doctrine/inflector` dependency be removed from composer.json, too?

**Comment by xabbuh** [comment]
@W0rma You are right, done in #2201.

**Comment by W0rma** [comment]
@xabbuh Can the configuration options "templating" and "inflector" be removed from "service" in 3.0 or will they become deprecated in a 3.x release (https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/DependencyInjection/Configuration.php#L118)?

**Comment by W0rma** [comment]
@xabbuh Btw thanks a lot for working hard on version 3.0 👍

**Comment by xabbuh** [comment]
@W0rma Thank you for your valuable input. I have deprecated the `fos_rest.service.inflector` option in #2204. I am currently looking into how to deal with the `fos_rest.service.templating` option.

**Comment by xabbuh** [comment]
see #2202

**Pull request merged**
